### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by Nobeernogman** [Tzahi12345/YoutubeDL-Material#231]
Sadly it wont work for me anymore.  Tips?

2020-10-11T07:59:47.313Z ERROR: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -o video/%(title)s.mp4 --write-info-json --print-json -f best[ext=mp4] http://www.youtube.com/watch?v=WR0WdTBQJGo
2020-10-11T08:00:12.398Z ERROR: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -o video/%(title)s.mp4 --write-info-json --print-json -f best[ext=mp4] http://www.youtube.com/watch?v=WR0WdTBQJGo

**Comment by Tzahi12345** [comment]
Sorry for the late response, can you give more info on your setup? Are you using Docker and what OS are you using?

**Comment by Nobeernogman** [comment]
> Sorry for the late response, can you give more info on your setup? Are you using Docker and what OS are you using?

No problem :-) Sorry for the lack of information.
youtube-dl-material did work, downloaded a few files, then i did not use it for about 2 weeks, now its just that error.

Unraid 6.8.3
https://i.imgur.com/afHGJ3o.png

**Comment by y2klol** [comment]
I am having a similar issue with the docker-compose 
Docker version 19.03.8, build afacb8b7f0
docker-compose version 1.25.5, build 8a1c60f6
Linux cube 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

version: "3.7"

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge

########################### SERVICES
services:
# All services / apps go below this line
    ytdl_material:
        environment: 
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: always
        networks:
            - t2_proxy
        volumes:
            - ./appdata:/app/appdata
            - ./audio:/app/audio
            - ./video:/app/video
            - ./subscriptions:/app/subscriptions
            - ./users:/app/users
        ports:
            - "8998:8998"
        image: tzahi12345/youtubedl-material:latest
```
I have been playing with the ports since I'm trying to get it to work with traefik. I can access the youtubedl page but I get "download failed" error when trying to download. I'm getting no logs in the settings menu (it's all blank).

**Comment by Ombrelin** [comment]
Hello, 
I have exactly the same issue, my setup is Docker + Traefik :
```yml
  ytdl:
    environment: 
        ALLOW_CONFIG_MUTATIONS: 'true'
    restart: always
    volumes:
        - /home/arsene/youtube-dl/appdata:/app/appdata
        - /mnt/DISK2/Videotheque/Musique:/app/audio
        - /mnt/DISK2/Videotheque/Youtube:/app/video
        - /home/arsene/youtube-dl/subscriptions:/app/subscriptions
        - /home/arsene/youtube-dl/users:/app/users
    image: tzahi12345/youtubedl-material:latest
```

And the error showing in the logs : 
> 2020-10-30T12:58:33.495Z ERROR: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -o audio/%(title)s.%(ext)s --write-info-json --print-json -f best[ext=mp4] http://www.youtube.com/watch?v=n8X9_MgEdCg

**Comment by Tzahi12345** [comment]
@Ombrelin @y2klol @Nobeernogman Can you test out the latest `nightly` and see if it's fixed? After the recent DMCA's, the old updating system failed, it should be fixed now!

**Comment by Ombrelin** [comment]
Hey, I just tested with the `nightly` tag and everthing worked just fine ! 
Thank you for fixing this so quickly 🤗

**Comment by Tzahi12345** [comment]
Great to hear! Will close the issue.

**Comment by ibrahimk157** [comment]
Had this issue, updated to the nightly build, fixed it temporarily and now the issue is back.
