### ISSUE TITLE
[BUG] The same video is displayed in several. 

### ISSUE THREAD

**Issue by arithxp** [Tzahi12345/YoutubeDL-Material#415]
**Describe the bug**
The webpage is not responding.
The same video is displayed in several. 

**To Reproduce**
1. git clone https://github.com/Tzahi12345/YoutubeDL-Material.git
2. docker build -t ytdl:0.1 .
3. edit docker-compose.yml file (container name, mount path)
4. goto YTDL setting. select yt-dlp, use cookies
5. then Subscribe to about 15 channels. (It happened when I subscribed to a new channel or new video)
6. After a few hours the webpage becomes unresponsive.
7. So I restarted the container.

**Expected behavior**
The same video appears.

**Screenshots**
![55](https://user-images.githubusercontent.com/6009737/128521045-efc0ee4f-b46c-43e1-85ec-10de111a60e4.png)

**Environment**
- After downloading git clone, I made an image with docker build.

**Additional context**
I don't know if it's a virtual machine problem or a Docker problem.
(I'm running an Ubuntu virtual machine on xcp-ng, and I've set up 6 cpu and 8 GB of ram. Also, I am using a Synology NAS, and it is mounted through smb.)
The webpage goes unresponsive within a few hours of running the container.
So I had no choice but to restart the container. I don't know if that's the reason, but the same video appears multiple times. 
```
version: "2"
services:
    ytdl_material:
        environment:
            ALLOW_CONFIG_MUTATIONS: 'true'
            ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
            ytdl_use_local_db: 'false'
            write_ytdl_config: 'true'
        restart: always
        volumes:
            - ./appdata:/app/appdata
            - /mnt/z/audio:/app/audio
            - /mnt/z/video:/app/video
            - /mnt/z/subscriptions:/app/subscriptions
            - ./users:/app/users
        ports:
            - "8998:17442"
        container_name: ytdl
        image: ytdl:0.1
    ytdl-mongo-db:
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
        logging:
            driver: "none"
        container_name: mongo-db
        volumes:
            - ./db/:/data/db
```

**Comment by QrchackOfficial** [comment]
> NOTE: It is currently recommended that you use the nightly tag on Docker. To do so, simply update the docker-compose.yml image field so that it points to tzahi12345/youtubedl-material:nightly.

Make sure you're using the nightly, this bug has been fixed recently.

**Comment by Tzahi12345** [comment]
@QrchackOfficial is right, this should be fixed in the latest `nightly`. It seems like you pulled from master which is good, but if you did so a week ago you wouldn't have this fix. Let me know if you still have this problem and I'll reopen.

**Comment by arithxp** [comment]
> 
> 
> @QrchackOfficial is right, this should be fixed in the latest `nightly`. It seems like you pulled from master which is good, but if you did so a week ago you wouldn't have this fix. Let me know if you still have this problem and I'll reopen.

I downloaded the modified source from the git repository and built it.
Checked and downloaded "Fixed bug where subscription videos would get duplicated" in the changes.
![56](https://user-images.githubusercontent.com/6009737/128651555-61028bda-e508-4ace-a12f-96f3202fd0e1.png)
(KST. UTC+9)
So I think it's a bug. I don't know if mongo-db is the problem.

**Comment by Tzahi12345** [comment]
Oh ok I'll re-open then! I doubt it's a MongoDB thing, probably a logic issue. Are these duplicated files or it's just a DB thing? We do have logic specifically to avoid adding records to the subscriptions table if the file already exists there (based on its path).

**Comment by arithxp** [comment]
> 
> 
> Oh ok I'll re-open then! I doubt it's a MongoDB thing, probably a logic issue. Are these duplicated files or it's just a DB thing? We do have logic specifically to avoid adding records to the subscriptions table if the file already exists there (based on its path).

There is only one file.
![51](https://user-images.githubusercontent.com/6009737/128866179-5f71e8e6-7129-4816-a0a9-f8eea07f1a6b.png)
A single file is displayed as multiple videos in the list.
![52](https://user-images.githubusercontent.com/6009737/128866812-3cf86b76-5315-47f3-8ff1-27dcca0ce64b.png)

**Comment by andreicociuba** [comment]
i think if for some reason the youtube-dl times out or simply takes too long, theres a bunch of unfulfilled promises that are uncatched, but entries are still made into the database as if it were a new video.

eventually, youtube-dl either finishes, or is retried and resumes from part-file or whatever...... there is just one downloaded file, but it is referenced with multiple ids in the database. 

Also, if you delete one of them, all of them fail to play, because the backend file has been deleted.

currently, until this is fixed, i am trying to use the http api to detect multiple videos with the same titles and then use same api to mark for deletion and redownload........ in the web interface, that seems to be the easiest solution, but i already have like 20 videos that have couple hundred entries each, so doing it by hand is deffinitely more time consuming than automating it via api.....

**Comment by arithxp** [comment]
There is a reason I thought it might be a mongo-db problem.

![52](https://user-images.githubusercontent.com/6009737/129130812-49ab49fd-2561-467a-9734-329eeedabe3b.png)
![53](https://user-images.githubusercontent.com/6009737/129130819-535b1a04-20f9-4ca0-b893-bcb189d96b44.png)
![54](https://user-images.githubusercontent.com/6009737/129131249-1933b245-7e11-4ee9-bc4a-f58878d26fd8.png)

Subscriptions and playlists combined are less than 20,000.
(even combining json and webp files)

**Comment by Tzahi12345** [comment]
Hi sorry for the delay, I've been on vacation.

I added some logic that forces the duplicate file check and the actual insertion of the file record to be atomic, meaning they both happen at the same time. [See the commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/ce3d540633c6616c6f8cec94efb7d910cebd7032). Let me know if this fixes the issue! Perhaps we can also use a simple check to remove duplicate files at startup.

**Comment by GlassedSilver** [comment]
> 
> 
> Hi sorry for the delay, I've been on vacation.
> 
> I added some logic that forces the duplicate file check and the actual insertion of the file record to be atomic, meaning they both happen at the same time. [See the commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/ce3d540633c6616c6f8cec94efb7d910cebd7032). Let me know if this fixes the issue! Perhaps we can also use a simple check to remove duplicate files at startup.

I've been experiencing this issue as well, so this would be a welcome fix, I'll try it out as soon as I get to it.
I think the duplicate check is most assuredly something that ought to be integrated, however I would do such a thing as a routine that gets queued up (maybe along with other background maintenance tasks) that might get their own settings page tab where you can check on the progress of maintenance tasks, see their schedules and run them manually.

I would REALLY also advise to get a button to gracefully pause any download tasks (e.g. finish current jobs and pause starting new ones until deactivated again).
Such a toggle should persist until restart. Optionally this could be set to "always on until deactivated", so a restart would not auto-disable the maintenance mode. This could be really helpful in troubleshooting an installation.

I might make a separate issue from it if you prefer, but I wanna roll the idea first and hear if it's something you may have been wondering yourself already anyways.

Furthermore, I think I might be free tonight for the call we originally planned. Can't say exactly when, but the next time I see you in Discord I'll hit you up and the moment we both have time we could go over my setup and everything else if that's cool with you?

**Comment by QrchackOfficial** [comment]
While we're talking about this, I've had my json database corrupted due to bad memory in my server, after recovering from backup of the db I have entries that don't have a matching file since it was already deleted. I think it would be worthwhile to also check for any entries for which the files don't exist anymore. Maybe on container startup, or just a button settings.

**Comment by GlassedSilver** [comment]
Good idea, however we need to be careful with deciding how we present found errors and what to do with them automatically and what to do manually.

I would for example ALWAYS steer clear of auto-deleting db entries for which we don't find files. That should be a manual user choice always. And one that is absolutely clear and with the context. Not "Plex-style" — "empty trash bin" and you don't even know what gets tossed out.

I think this is a good example of manual user maintenance UI territory possibly getting introduced.

**Comment by Tzahi12345** [comment]
I like this approach of having asynchronous tasks in a queue to handle stuff like (duplicated or missing DB entries). There can be one to also detect entries for deleted files, but as @GlassedSilver mentioned this shouldn't be automatic. Rather, it should be confirmed through the UI. I think this deserves an issue for sure, with at least these 3 tasks to begin with as well as settings for each task.

@QrchackOfficial was this through MongoDB? Do you think it was corrupted for reasons outside YTDL-M?

**Comment by QrchackOfficial** [comment]
It was through local-db.json, as I haven't had luck migrating. I'm on reverse proxy, so localhost:port isn't a thing when the app and the db are on different containers and ports aren't forwarded. Haven't had the time to set it up properly. Basically, I have 2+1GB of DDR3 on my 1st gen i3 based server, where 1GB is fine, but 2GB spits memtest errors and contributes to the fact that I have kernel panics at random. Basically resulting in the files open at the moment being rewritten with all 0x00 hex.  On one particularly bad day I had to recover the ext4 partition, and at the moment:
- despite archive being enabled, videos I've watched and clicked "delete forever" are re-downloaded for my subscriptions, or at least one (where archive.txt was corrupted and I've had to manually wipe the file)
- I regularly get this in the log:
```
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 27)
(node:20) UnhandledPromiseRejectionWarning: TypeError: downloads.find is not a function
    at /app/app.js:2393:41
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at compression (/app/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at /app/app.js:1434:9
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
```
- I also regularly get terminated by SIGKILL in the logs, presumably due to low RAM. I have monitoring set up and youtubedl-material seems to be trying to use _everything_ indefinitely, all the 3GB of RAM + 4GB of swap, and then it gets killed:
![image](https://user-images.githubusercontent.com/3584315/129460062-d36357c2-8a68-4422-8f29-cd71abc1ae70.png)
Swap I/O and usage correlate to the memory usage spikes. You can see allocated memory vs out-of-memory kills here:
![image](https://user-images.githubusercontent.com/3584315/129460096-7bc55c54-b2d8-4e04-b44e-159b6a02d99b.png)

Here's CPU usage by application. Node from youtubedl-material is consistently using 25% of the CPU, while every other service is happy with 0.2-1%
![image](https://user-images.githubusercontent.com/3584315/129460137-73419750-ff07-43bb-ab00-c505ff873b2e.png)

Basically, youtubedl-material is the biggest resource hog on my whole server for some reason. Here are the Docker limits for the container:
![image](https://user-images.githubusercontent.com/3584315/129460197-725396d0-1ac1-4afc-b6cf-399438a3a8b1.png)

My settings:
- Subscription check interval - 3000 (increased from 300 recently, seems to have helped a lot)
- Download delay - 300
- Download rate limit - 200K
- Database location - Local (Files - 160, Subscriptions - 10)

I get this regularly for all my subscriptions:
```
2021-08-14T17:54:11.851Z ERROR: Command was killed with SIGKILL (Forced termination): /app/node_modules/youtube-dl/bin/youtube-dl -i -o subscriptions/channels/Louis Rossmann/%(title)s.%(ext)s -ciw --write-info-json --print-json -f bestvideo[height<=1440]+bestaudio/best[height<=1440] --merge-output-format mp4 --mark-watched --download-archive --dateafter now-2weeks --cookies appdata/cookies.txt --write-thumbnail --sleep-interval 300 -r 200K https://www.youtube.com/user/rossmanngroup/videos
```
Despite that, videos get downloaded (and actually re-download even after I "delete forever"). However all manual downloads fail since the ext4 recovery situation. I also recall my virtual 100GB disk (where Docker and ytdm is running) being completely full and had to shuffle things around. I guess I'll just wipe the whole instance, and set it up again from scratch tbh, it's a mess here.

**Comment by QrchackOfficial** [comment]
Is there any way I can set the node server (in a config file or whatever) to not eat every imaginable resource so it doesn't get killed though? Should help a little. This graphs are with no one accessing the server, no playback no nothing, likely just subscriptions downloading. I think it might be downloading everything at once, these youtube-dl instance launches should probably be queued so it doesn't kill everyone's servers.

**Comment by Tzahi12345** [comment]
The local DB is very prone to this which is why we added MongoDB support in the first place to avoid these shenanigans. I don't think port forwarding is required though, and they're usually going to sit on separate containers anyways. The trick is to use the container name in the MongoDB like so:

```
mongodb://<container name>:27017/?compressors=zlib
```

Just put your container name in there and it should work in theory.

But let me address your problems one by one:

>despite archive being enabled, videos I've watched and clicked "delete forever" are re-downloaded for my subscriptions, or at least one (where archive.txt was corrupted and I've had to manually wipe the file)

Can you share an example of the text file being corrupted? Maybe if I see it, it would be easier to see what went wrong.

> I regularly get this in the log: TypeError: downloads.find is not a function

Should be fixed in #420 as we are reworking the old system for downloads so this error will go away.

>Here's CPU usage by application. Node from youtubedl-material is consistently using 25% of the CPU, while every other service is happy with 0.2-1%

If you turn off subscriptions does this number go down? This may just be a duplicate of #122 which may have a difficult solution besides what you already did (extending subscriptions check interval). What may be the real issue here is ffmpeg, which is very CPU heavy and is probably used in every download. There are ways to avoid this (`-f,,best` as a custom arg should do) but you're giving up a lot in terms of video quality.

Your solutions should help mitigate this but it's hard to get around in general. I think the best we can do is develop ways to manage it, like #420 attempts to achieve. At the very least, your DB problems should be relatively easy to fix which will at least make your life easier in that regard as maintaining backups sucks.

**Comment by arithxp** [comment]
I've been very busy lately, so I'm late to check. sorry.
I checked today and the problem seems to have been resolved. thank you.

**Comment by arithxp** [comment]
> 
> 
> I've been very busy lately, so I'm late to check. sorry.
> I checked today and the problem seems to have been resolved. thank you.

omg... again.....
i don't know why this happen

**Comment by Tzahi12345** [comment]
You're still seeing this problem?

**Comment by arithxp** [comment]
Yes. I had the same problem again.
A problem occurred when adding a new subscription.
The web page became slow while receiving the video, and if I check later, multiple videos are registered as duplicates.
And when I unsubscribe, can't I decide whether to delete the video or not?

**Comment by Tzahi12345** [comment]
Do you have any custom args or custom output set either for subscriptions or globally? I think I know what's causing this bug.

**Comment by arithxp** [comment]
> 
> 
> Do you have any custom args or custom output set either for subscriptions or globally? I think I know what's causing this bug.

Ah. Yes, I did two settings.
Main-Download delay : 30 (or 60, Currently empty. There was a problem, so I had to set it up differently every time I created a new container.)
Downloader-Download rate limit : 10000k (or 20000k. Currently empty. Same as above.)

Neither of them set any options while creating a new container this time. Let's see if this is the cause of the problem.

**Comment by Tzahi12345** [comment]
In my case I had a custom output that ended up duplicating files but in your case you don't have that so I'm not so sure that's what is happening here, but I do have another idea related to the file name. Would you mind sharing the .info.json file for one of the duplicated videos?

**Comment by arithxp** [comment]
> 
> 
> In my case I had a custom output that ended up duplicating files but in your case you don't have that so I'm not so sure that's what is happening here, but I do have another idea related to the file name. Would you mind sharing the .info.json file for one of the duplicated videos?

> 
> 
> ![52](https://user-images.githubusercontent.com/6009737/128866812-3cf86b76-5315-47f3-8ff1-27dcca0ce64b.png)


This is the .info.json file of the screenshot I posted earlier. 
https://tmpstorage.com/download/file/9xiw7nkuq6
( If the download does not work, click the "다운로드" button on the https://tmpstorage.com/download/9xiw7nkuq6 page. )

**Comment by Tzahi12345** [comment]
Thanks for the additional info!

I think I have finally fixed this. I believe it had to do with inconsistent path formatting (double backslash `\\` vs forward slash `\` delimiters) during the process of importing unregistered files. Now these differences in paths should be eliminated, and the system for importing unregistered files is more robust. [See commit here.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/6eb1e2f898ad5f1a6a9c506aad382ceefab3cab3)

Let me know if this works! One way to verify is to enable verbose logging before updating your `nightly` and restarting the container. You may see a lot of log messages of files being imported. Once you update, these should disappear.

**Comment by arithxp** [comment]
Thank you for your efforts to fix the bug.

After deleting the existing container, I deleted all images with docker system prune -a command. After that, I downloaded it from the git repository and built it. Therefore, I think it is the latest image.

I've subscribed to two new channels for testing on the latest build of YTDL. It seemed to work fine at first. Hundreds of videos were received after a few hours, and after checking, it seems that there is still a problem. 

![771](https://user-images.githubusercontent.com/6009737/130477288-104a4316-55b2-47fd-b192-eaea26927c35.png)

**Comment by QrchackOfficial** [comment]
I've set up a staging instance with mongodb a couple of hours ago (on nightly). It seems like the duplicated videos get two different `_id` fields and contain the same JSON data. For now, I hand-remove them with Compass.

**Comment by Tzahi12345** [comment]
I pushed another change that will hopefully fix this. Beforehand, the logic to avoid duplicates used the path to the file which was inconsistent as mentioned above due to different formatting. Now this is done just using the video URL ([see commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/f9b1414460ed6cc4b25e524e1bfc7e3d97767c80)).

Note that #420 should fix this problem regardless once that gets merged.

**Comment by QrchackOfficial** [comment]
Well that worked a treat. Thanks!

**Comment by arithxp** [comment]
> 
> 
> I pushed another change that will hopefully fix this. Beforehand, the logic to avoid duplicates used the path to the file which was inconsistent as mentioned above due to different formatting. Now this is done just using the video URL ([see commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/f9b1414460ed6cc4b25e524e1bfc7e3d97767c80)).
> 
> Note that #420 should fix this problem regardless once that gets merged.

I built the latest image and did a clean install by deleting the appdata, db, and users folders.
![61](https://user-images.githubusercontent.com/6009737/130668847-2d9e9b07-eac3-4161-9822-e5beac1c27ff.png)
Still have the same problem. As you can see in the screenshot, a huge amount of duplicate videos were registered.
Is there any information I can provide to fix the bug?

```
http://192.168.29.190:8998/#/player;uid=f834b6f0-2cba-48d8-9f57-244d7f0e73fe;sub_id=a8597c19-18d5-4d2d-9f3f-4b6fa68de384
http://192.168.29.190:8998/#/player;uid=3aad3af1-619b-4911-bb03-676f91b2bd57;sub_id=a8597c19-18d5-4d2d-9f3f-4b6fa68de384
http://192.168.29.190:8998/#/player;uid=23f0f799-7c50-4475-b609-1c401f8efbf1;sub_id=a8597c19-18d5-4d2d-9f3f-4b6fa68de384
```

**Comment by GlassedSilver** [comment]
>     * edit
>       I did a clean install by rebuilding the image and erasing all settings.
>       And if I spend enough time each time I subscribe to a channel that youtube-dl doesn't use too many resources, it shouldn't be a problem.

Sorry if I don't quite understand, but does that mean you consider this (so far from what you can tell) as solved?

**Comment by arithxp** [comment]
> Sorry if I don't quite understand, but does that mean you consider this (so far from what you can tell) as solved?

no. It's not resolved.
What I'm talking about is no different than creating a new container when something goes wrong. (It is like attaching duct tape to the problem area.)
Even if you wait enough time to register a channel, there may be problems, and the solution is to delete the problematic video and download it again.
I usually unsubscribe and re-subscribe to channels that have problems. (You have to rename the folder before unsubscribing so it doesn't get deleted.) This was the solution I could do.

And can't you change the address of the thumbnail image from the YouTube server to your own server? If the video has been deleted, the thumbnail image will not be displayed. 
![711](https://user-images.githubusercontent.com/6009737/130732549-d19c8893-3643-409f-bd49-38010b4ca7ae.png)

**Comment by arithxp** [comment]
> 
> 
> I pushed another change that will hopefully fix this. Beforehand, the logic to avoid duplicates used the path to the file which was inconsistent as mentioned above due to different formatting. Now this is done just using the video URL ([see commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/f9b1414460ed6cc4b25e524e1bfc7e3d97767c80)).
> 
> Note that #420 should fix this problem regardless once that gets merged.

I think my problem has been solved.
However, the problem recurred when the YTDL frontend fell into unresponsiveness. (It seems to be a disk I/O problem or a network I/O problem, as the problem occurs when receiving a large amount of video. I'm not sure). In this case, you could avoid the problem by re-subscribing to that channel.
Other than the above problem, it worked very correctly. Thank you.

**Comment by GlassedSilver** [comment]
You might have pulled a slightly outdated nightly build there before, because there have been two builds in rapid succession and sometimes DockerHub takes a little while to pick up on a new build.

Glad to hear it seems solved for you. As for UI responsiveness, that as well is something that yours truly is constantly trialing with a database of... oh... you know.... over 30k videos :D  (and atm 48 subscriptions)

It's something that is currently being looked into a lot more, so maybe that helps you rest a little easier. ;)

#420 will definitely help a lot in this regard as well. Overall YoutubeDL-Material has undergone already one MASSIVE increase in performance on large databases both thanks to migrating to MongoDB which is a fair step up from running off of json files as well as the recent change to load the UI right away on container start rather than waiting for a bunch of background processes to finish which for heavy users like me meant something between 10-20 minutes of start up time or even more until I could get into the UI. (and more it was towards the end for sure...)

We've come a long way and I'm very optimistic about more optimizations happening that'll make using the application even more fun and reliable. :)
