### ISSUE TITLE
Issue starting webui on docker compose[BUG]

### ISSUE THREAD

**Issue by Glynax** [Tzahi12345/YoutubeDL-Material#559]
**Describe the bug**
I just spun this up a few nights ago, it worked great (aside from me fighting with trying to get m4a best audio only with meta data and embedded thumbnails.. Would appreciate any help on that as well) but I've rebooted a few times and docker-compose down and pull and up and I keep getting either no error but nothing works (playlists or subscriptions) or I get this error in the docker logs 

`root@debassist:/opt/ytdlMaterial# docker-compose up
Creating network "ytdlmaterial_default" with the default driver
Creating ytdlmaterial_ytdl_material_1 ... done
Attaching to ytdlmaterial_ytdl_material_1
ytdl_material_1  | 2022-04-23T21:24:18: PM2 log: Launching in no daemon mode
ytdl_material_1  | 2022-04-23T21:24:18: PM2 log: [Watch] Start watching YoutubeDL-Material
ytdl_material_1  | 2022-04-23T21:24:18: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
ytdl_material_1  | 2022-04-23T21:24:18: PM2 log: App [YoutubeDL-Material:0] online
ytdl_material_1  | 2022-04-23T21:24:21.570Z INFO: YoutubeDL-Material v4.2 started on PORT 17442
ytdl_material_1  | TypeError: req.isAuthenticated is not a function
ytdl_material_1  |     at /app/app.js:1321:24
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
ytdl_material_1  |     at optionalJwt (/app/app.js:736:12)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
ytdl_material_1  |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at /app/node_modules/express/lib/router/index.js:281:22
ytdl_material_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/index.js:275:10)
ytdl_material_1  |     at compression (/app/node_modules/compression/index.js:220:5)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:323:13)
ytdl_material_1  |     at /app/node_modules/express/lib/router/index.js:284:7
ytdl_material_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
ytdl_material_1  | TypeError: req.isAuthenticated is not a function
ytdl_material_1  |     at /app/app.js:1321:24
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
ytdl_material_1  |     at optionalJwt (/app/app.js:736:12)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
ytdl_material_1  |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at /app/node_modules/express/lib/router/index.js:281:22
ytdl_material_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/index.js:275:10)
ytdl_material_1  |     at compression (/app/node_modules/compression/index.js:220:5)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:323:13)
ytdl_material_1  |     at /app/node_modules/express/lib/router/index.js:284:7
ytdl_material_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
ytdl_material_1  | TypeError: req.isAuthenticated is not a function
ytdl_material_1  |     at /app/app.js:1658:26
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
ytdl_material_1  |     at optionalJwt (/app/app.js:736:12)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
ytdl_material_1  |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at /app/node_modules/express/lib/router/index.js:281:22
ytdl_material_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/index.js:275:10)
ytdl_material_1  |     at compression (/app/node_modules/compression/index.js:220:5)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:323:13)
ytdl_material_1  |     at /app/node_modules/express/lib/router/index.js:284:7
ytdl_material_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
ytdl_material_1  | TypeError: req.isAuthenticated is not a function
ytdl_material_1  |     at /app/app.js:1658:26
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
ytdl_material_1  |     at optionalJwt (/app/app.js:736:12)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
ytdl_material_1  |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at /app/node_modules/express/lib/router/index.js:281:22
ytdl_material_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/index.js:275:10)
ytdl_material_1  |     at compression (/app/node_modules/compression/index.js:220:5)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:323:13)
ytdl_material_1  |     at /app/node_modules/express/lib/router/index.js:284:7
ytdl_material_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
ytdl_material_1  | TypeError: req.isAuthenticated is not a function
ytdl_material_1  |     at /app/app.js:1321:24
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
ytdl_material_1  |     at optionalJwt (/app/app.js:736:12)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
ytdl_material_1  |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at /app/node_modules/express/lib/router/index.js:281:22
ytdl_material_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/index.js:275:10)
ytdl_material_1  |     at compression (/app/node_modules/compression/index.js:220:5)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:323:13)
ytdl_material_1  |     at /app/node_modules/express/lib/router/index.js:284:7
ytdl_material_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
ytdl_material_1  | TypeError: req.isAuthenticated is not a function
ytdl_material_1  |     at /app/app.js:1321:24
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
ytdl_material_1  |     at optionalJwt (/app/app.js:736:12)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
ytdl_material_1  |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at /app/node_modules/express/lib/router/index.js:281:22
ytdl_material_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
ytdl_material_1  |     at next (/app/node_modules/express/lib/router/index.js:275:10)
ytdl_material_1  |     at compression (/app/node_modules/compression/index.js:220:5)
ytdl_material_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ytdl_material_1  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:323:13)
ytdl_material_1  |     at /app/node_modules/express/lib/router/index.js:284:7
ytdl_material_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
^CGracefully stopping... (press Ctrl+C again to force)
Stopping ytdlmaterial_ytdl_material_1 ... done
`
**To Reproduce**
1. Go to docker compose with these settings 
2. `version: "2"
services:
    ytdl_material:
        environment: 
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: unless-stopped
        volumes:
            - ./appdata:/app/appdata
            - /media/nfs/The_Flash/ytdl/audio:/app/audio
            - /media/nfs/The_Flash/ytdl/videos:/app/video
            - /media/nfs/The_Flash/ytdl/subscriptions:/app/subscriptions
            - ./users:/app/users
        ports:
            - "8998:17442"
        image: tzahi12345/youtubedl-material:nightly`
3. Type 'docker-compose up'

**Expected behavior**
I expected the web ui to work and allow me to download youtube channels with youtube dlp
**Screenshots**
![image](https://user-images.githubusercontent.com/7043861/164946585-8b60a002-6895-4b5b-ae95-d7affd883ef9.png)

**Environment**
- YoutubeDL-Material version
- Docker tag: <tag> (optional)
   See above
   Also using a local mongodb docker that it is successfully connected to as I intend to use this to handle many large channels and subscriptions once I'm up and running

Ideally you'd copy the info as presented on the "About" dialogue
in YoutubeDL-Material.
(for that, click on the three dots on the top right and then
check "installation details". On later versions of YoutubeDL-
Material you will find pretty much all the crucial information
here that we need in most cases!)

**Additional context**
Add any other context about the problem here. For example, a YouTube link.
for a test I'm trying to get this channel (or even just a small playlist for a test) in m4a audio only with metadata and embedded thumbnails. And.. Playlists just try to load forever never showing videos and subscriptions do the same https://www.youtube.com/playlist?list=PLezvkLNQcE8qNTQb5LI_0wywye519OYSV or https://www.youtube.com/user/djearworm/videos

**Comment by GlassedSilver** [comment]
can confirm this, I think one of the dependencies updated in a recent PR (probably by dependabot) aren't playing nice with the recent manual PRs that got tested against a different set of dependencies.

I'll look into this and revert some changes and see if it fixes this issue.

**Comment by Tzahi12345** [comment]
Looks like the issue is `TypeError: req.isAuthenticated is not a function`. I had updated passport, looks like usage might be changed but I'll hotfix this real quick.

**Comment by Tzahi12345** [comment]
Should be fixed but I can't reproduce... Mind testing this out once the nightly updates? Should take about an hour.

**Comment by Glynax** [comment]
> Should be fixed but I can't reproduce... Mind testing this out once the nightly updates? Should take about an hour.

Nope, pulled the latest nightly and it's the same error. Did I not wait long enough?

**Comment by Tzahi12345** [comment]
Ugh, looks like it failed to commit for some reason, now I actually pushed it to master. In an hour that should be ready :)

**Comment by Glynax** [comment]
Alright that's working again thanks. Before I close it could you help me with my arguments? I still can't figure out how to rip audio only with metadata and thumbnails. I have add metadata which I think works but embed thumbnail just isn't

**Comment by Tzahi12345** [comment]
Are you talking about `--add-metadata`? According to youtube-dl docs that's [only for videos](https://github.com/ytdl-org/youtube-dl#post-processing-options).

**Comment by Glynax** [comment]
Ah I thought it worked for audio for some reason. I still can't get embed thumbnail to work though I've googled several things and it just isn't embedding no matter what audio format it is.

**Comment by GlassedSilver** [comment]
Maybe yt-dlp tries to add a webp image into the audio file and the container may not support that image format. IDK

Maybe you look for support at the yt-dlp repo, because they are the ones who maintain the code to embed art into the downloaded video and audio files. (well, at least in your case, since you use yt-dlp, which is in my opinion a good choice)

**Comment by Glynax** [comment]
> Maybe yt-dlp tries to add a webp image into the audio file and the container may not support that image format. IDK
> 
> Maybe you look for support at the yt-dlp repo, because they are the ones who maintain the code to embed art into the downloaded video and audio files. (well, at least in your case, since you use yt-dlp, which is in my opinion a good choice)

Alright I'll give that a shot. Thank you so much for your help!
